## replace diana with the user on your computer
#user: "{{ host_user }}"
user: "{{ ansible_env['USER']}}"

#
# Miscellaneous
#

# whether to enable bluetooth or not
# true or false
enable_bluetooth: true

# Audio Server
# Weather to use pipewire or pluseaudio
# pipewire or pluseaudio
audio_server: pipewire

# Nvidia users, buckle up!
# Whether to use the proprietary Nvidia drivers or to keep the open source Nouveau drivers
# Beware that usage of the proprietary drivers, which are out of tree, WILL TAINT THE KERNEL!
# true or false
proprietary_nvidia_drivers: false

default_shell: zsh  # Change to the desired default shell, e.g., zsh or bash

icons:
  cursor_icons_package: bibata-cursor-theme-bin # AUR ONLY CURRENTLY
  cursor_icons_theme: Bibata-Modern-Ice
  # available cursor sizes: 16 20 22 24 28 32 40 48 56 64 72 80 88 96
  cursor_icons_size: 24
  
pacman:
  parallel_downloads: 5 # Adjust as needed
  enable_multilib: false  # Set to false if you don't want to enable multilib
  # set aur helper
  # supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
  aur_helper: yay
  # Option to enable the chaotic-aur: https://aur.chaotic.cx/ or keep it disabled
  # true of false 
  chaotic_aur: false


pre_tasks:
  - pacman
  - vm_detection
  - shell_update
  - gpu_drivers
  - laptop_workarounds

default_roles:
  - system
  - bluetooth
  - audio
  - zsh
  - oh-my-posh
  - fastfetch
  - helix
  - alacritty
  - nautilus
  - hyprland
  - ags
  - firefox
  - greetd
  - mission-center
  - zed
  - sunroof #vencord fork discord client
  - spotube #spotify open source client
  # - kvm # Virtal Machine setup

post_tasks:
  - aur_clean
