## replace diana with the user on your computer
user: "{{ host_user }}"

#
# Miscellaneous
#

# whether to enable bluetooth or not
# true or false
enable_bluetooth: true

# Audio Server
# Weather to use pipewire or pluseaudio
# pipewire or pluseaudio
audio_server: pipewire

# Framework Laptop Intel 13 Inch fix fn keys,brightness,sound buttons
# true or false
framework_laptop_intel_13inch: true

pacman:
  # set aur helper
  # supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
  aur_helper: yay
   
default_roles:
  - system
  - bluetooth
  - audio
  - zsh
  - oh-my-posh
  - fastfetch
  - helix
  - alacritty
  - nautilus
  - hyprland
  - ags
  - firefox

