---
- name: "Ags | {{ ansible_distribution }} | Install Ags"
  kewlfft.aur.aur:
    name: 
      - aylurs-gtk-shell
    state: present
  become: false

- name: "Ags | {{ ansible_distribution }} | Install dependency for Ags: greetd"
  community.general.pacman:
    name:
      - greetd
    state: present
  become: true
