---
- name: "Ags | {{ ansible_distribution }} | Install Ags"
  kewlfft.aur.aur:
    name: 
      - aylurs-gtk-shell
    community.general.pacman:
      name: 
        - greetd
    state: present
  become: true
