---
- name: "Ags | {{ ansible_distribution }} | Install Ags"
  kewlfft.aur.aur:
    name: 
      - aylurs-gtk-shell-git
      - bun-bin
      - matugen-bin
    state: present
  become: false

- name: "Ags | {{ ansible_distribution }} | Install dependency for Ags: greetd"
  community.general.pacman:
    name:
      - greetd
      - dart-sass
      - fd
      - brightnessctl
      - swww
      - gnome-bluetooth-3.0
      - libdbusmenu-gtk3
      - libnotify
      - libsoup3
      - networkmanager
      - power-profiles-daemon
      - upower
    state: present
  become: true
