---
- name: "Ags | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ags_distribution_config

- name: "Ags | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ags_distribution_config.stat.exists

- name: Configure Ags Greetd
  block:
    - name: Create greetd configuration directory
      file:
        path: /etc/greetd
        state: directory
      become: true

    - name: "Ags Greetd Configuration | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/greetd/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'config.toml.j2', dest: 'config.toml' }

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      become: true
      with_items:
        - greetd

    - name: Create directories and set ownership
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: '/var/cache/greeter', owner: 'greeter', group: 'greeter', mode: '0755' }
        
    - name: Copy ags user configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      loop:
        - { src: 'ags', dest: '', mode: '0644', directory_mode: '0755' }

    - name: Copy ags system configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      become: true
      loop:
        - { src: 'ags', dest: 'greetd', mode: '0644', directory_mode: '0755' }


- name: Manage User Pictures
  block:
    - name: "Copy pictures"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      become: true
      become_user: "{{ user }}"
      loop:
        - { src: 'wallpaper', dest: 'Pictures/', mode: '0644', directory_mode: '0755' }
        - { src: 'pfp', dest: 'Pictures', mode: '0644', directory_mode: '0755' }

    - name: Copy ags system configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      become: true
      loop:
        - { src: '{{ ansible_user_dir }}/Pictures/pfp/avatar.jpg', dest: '/var/lib/AccountsService/icons/{{ user }}', mode: '0644', directory_mode: '0755' }
