---
- name: "Ags | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ags_distribution_config

- name: "Ags | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ags_distribution_config.stat.exists

- name: Configure Ags Greetd
  block:
    - name: Create greetd configuration directory
      file:
        path: /etc/greetd
        state: directory
      become: true

    - name: "Ags Greetd Configuration | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/greetd/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'config.toml.j2', dest: 'config.toml' }

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      become: true
      with_items:
        - greetd

    - name: Create directories and set ownership
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: '/var/cache/greeter', owner: 'greeter', group: 'greeter', mode: '0755' }
        
    - name: Synchronize configuration files
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      loop:
        - { src: "ags", dest: "{{ ansible_user_dir }}/.config/" }
        - { src: "ags", dest: "/etc/greetd" }
      become: "{{ item.become | default(false) }}"


- name: Manage User Pictures
  block:
    - name: "Synchronize pictures"
      ansible.posix.synchronize:
        mode: push
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        recursive: yes
      become: true
      become_user: "{{ user }}"
      loop:
        - { src: 'wallpaper', dest: 'Pictures/' }
        - { src: 'pfp', dest: 'Pictures' }
        - { src: 'wallpaper/mountain.png', dest: '.config/background' }

    - name: Synchronize ags system configuration files
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      become: true
      loop:
        - { src: '{{ ansible_user_dir }}/Pictures/pfp/avatar.jpg', dest: '/var/lib/AccountsService/icons/{{ user }}' }
