---
- name: "Ags | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: ags_distribution_config

- name: "Ags | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: ags_distribution_config.stat.exists

#- name: "Ags | Configure Ags"
#  ansible.builtin.copy:
#    src: ags
#    dest: "{{ ansible_user_dir }}/.config/"
#    mode: "0644"
#    directory_mode: "0755"
#    force: true

- name: Configure Ags Greetd
  block:
    - name: Create greetd configuration directory
      file:
        path: /etc/greetd
        state: directory
      become: true

    - name: "Ags Greetd Configuration | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/greetd/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'config.toml.j2', dest: 'config.toml' }

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      become: true
      with_items:
        - greetd


- name: Manage User Pictures
  block:
    - name: "Copy pictures"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      become: true
      become_user: "{{ user }}"
      loop:
        - { src: 'wallpaper', dest: 'Pictures/', mode: '0644', directory_mode: '0755' }
        - { src: 'pfp', dest: 'Pictures', mode: '0644', directory_mode: '0755' }
        - { src: 'pfp/avatar.jpg', dest: '.config/avatar', mode: '0644', directory_mode: '0755' }
        - { src: 'wallpaper/mountain.png', dest: '.config/background', mode: '0644', directory_mode: '0755' }
