---
- name: System Maintenance
  block:
    - name: Upgrade system
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      become: true

    - name: Install Preliminary Dependencies | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - fakeroot
        - debugedit
        - base-devel

    - name: Install AUR Helpers and Rate-Mirrors Package | {{ ansible_distribution }}
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
      become: false
      loop:
        - "{{ pacman.aur_helper }}"
        - rate-mirrors-bin

- name: Chaotic AUR Setup
  block:
    - name: Setup Chaotic AUR Keys and Mirrorlist
      command: "{{ item.command }}"
      become: true
      loop:
        - { command: 'pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com' }
        - { command: 'pacman-key --lsign-key 3056513887B78AEB' }
        - { command: 'pacman -U --noconfirm https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' }
        - { command: 'pacman -U --noconfirm https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' }
      when: pacman.chaotic_aur

- name: Backup Configuration Files
  block:
    - name: Backup Mirrors Configuration Files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      become: true
      loop:
        - { src: '/etc/pacman.d/mirrorlist', dest: '/etc/pacman.d/mirrorlist.bak' }
        - { src: '/etc/pacman.d/chaotic-mirrorlist', dest: '/etc/pacman.d/chaotic-mirrorlist.bak' }
      when: item.dest != '/etc/pacman.d/chaotic-mirrorlist.bak' or pacman.chaotic_aur

- name: Generate and Update Mirrors List
  block:
    - name: Generate and Update Mirrors List
      shell: "rate-mirrors --allow-root --protocol https {{ item.repo }} | grep -v '^#' > /etc/pacman.d/{{ item.filename }}"
      become: true
      register: generate_mirrors
      changed_when: generate_mirrors.rc == 0
      loop:
        - { repo: 'arch', filename: 'mirrorlist' }
        - { repo: 'chaotic-aur', filename: 'chaotic-mirrorlist' }
      when: item.repo != 'chaotic-aur' or pacman.chaotic_aur

- name: Update pacman Configuration
  block:
    - name: Update pacman configuration file
      ansible.builtin.template:
        src: pre_tasks/package_manager/templates/pacman.conf.j2
        dest: /etc/pacman.conf
        owner: root
        group: root
        mode: 0644
      become: true
