---
- name: "KVM | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: kvm_distribution_config

- name: "KVM | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: kvm_distribution_config.stat.exists

- name: Configure and Start libvirtd Service
  block:
    - name: Enable, start, and restart libvirtd service
      systemd:
        name: libvirtd
        enabled: yes
        state: restarted
      become: true

    - name: Add user to libvirt group
      user:
        name: "{{ user }}"
        groups: libvirt
        append: yes
      become: true

    - name: Ensure libvirtd.conf settings
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      become: true
      loop:
        - { regexp: '^#?unix_sock_group = ', line: 'unix_sock_group = "libvirt"' }
        - { regexp: '^#?unix_sock_rw_perms = ', line: 'unix_sock_rw_perms = "0770"' }

- name: Manage Default Virtual Network
  block:
    - name: Ensure the default virtual network is started and autostarted
      command: "virsh net-{{ item }} default"
      become: true
      ignore_errors: yes
      loop:
        - start
        - autostart
