---
- name: Install Hyprland Packages | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - hyprcursor
    - hyprlang
    - hyprutils
    - hyprwayland-scanner
    - hyprland
    - hypridle
    - hyprlock
    - xdg-desktop-portal-hyprland
    - playerctl

- name: Install Hyprland AUR Dependencies | {{ ansible_distribution }}
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: "{{ pacman.aur_helper }}"
  become: false
  loop:
    - hyprshot

- name: Install Cursor Icons | {{ ansible_distribution }}
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: "{{ pacman.aur_helper }}"
  become: false
  loop:
    - "{{ icons.cursor_icons_package }}"

