---
- name: "Hyprland | {{ ansible_distribution }} | Install Hyprland"
  community.general.pacman:
    name:
      - hyprcursor
      - hyprlang
      - hyprutils
      - hyprwayland-scanner
      - hyprland
      - hypridle
      - hyprlock
      - xdg-desktop-portal-hyprland
      - playerctl
    state: present
  become: true

- name: "Hyprland AUR dependencies | {{ ansible_distribution }} | Install Hyprland AUR dependencies"
  kewlfft.aur.aur:
    name: 
      - hyprshot
    state: present
  become: false

- name: "Cursor Icons | {{ ansible_distribution }} | Install Cursor Icons"
  kewlfft.aur.aur:
    name: "{{ icons.cursor_icons_package }}"
    state: present
  become: false
