---
- name: "Hyprland | {{ ansible_distribution }} | Install Hyprland"
  community.general.pacman:
    name:
      - hyprcursor
      - hyprlang
      - hyprutils
      - hyprwayland-scanner
      - hyprland
      - xdg-desktop-portal-hyprland
    state: present
  become: true
