---
- name: "Hyprland | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: hyprland_distribution_config

- name: "Hyprland | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: hyprland_distribution_config.stat.exists

- name: Configure Hyprland
  block:
    - name: "Hyprland | Copy configuration files"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      loop:
        - { src: 'hypr', dest: '.config', mode: '0644', directory_mode: '0755' }
        - { src: 'hypr/scripts', dest: '.config/hypr/', mode: '0755', directory_mode: '0755' }

    - name: "Hyprland | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/hypr/config/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'autostart.conf.j2', dest: 'autostart.conf' }
        - { src: 'env_default.conf.j2', dest: 'environments/default.conf' }
        - { src: 'environment.conf.j2', dest: 'environment.conf' }

- name: Manage User Pictures
  block:
    - name: "Copy pictures"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/assets/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        mode: "{{ item.mode }}"
        directory_mode: "{{ item.directory_mode }}"
        force: true
      become: true
      become_user: "{{ user }}"
      loop:
        - { src: 'wallpaper', dest: 'Pictures/', mode: '0644', directory_mode: '0755' }
        - { src: 'pfp', dest: 'Pictures', mode: '0644', directory_mode: '0755' }
        - { src: 'pfp/avatar.jpg', dest: '.config/avatar.jpg', mode: '0644', directory_mode: '0755' }
        - { src: 'wallpaper/mountain.png', dest: '.config/background.png', mode: '0644', directory_mode: '0755' }

# on hold tell 0.42 release
# - name: Manage Hyprland dynamic cursors
#   block:
#     - name: Update hyprpm package list
#       command: hyprpm update
      
#     - name: Add hypr-dynamic-cursors repository
#       command: hyprpm add https://github.com/virtcode/hypr-dynamic-cursors

#     - name: Install hypr-dynamic-cursors
#       command: hyprpm install dynamic-cursors

#     - name: Enable dynamic cursors
#       command: hyprpm enable dynamic-cursors
