---
- name: "Hyprland | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: hyprland_distribution_config

- name: "Hyprland | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: hyprland_distribution_config.stat.exists

- name: Configure Hyprland
  block:
    - name: "Hyprland | Sync configuration files"
      ansible.posix.synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        recursive: yes
      loop:
        - { src: 'hypr', dest: '.config/' }
        - { src: 'hypr/scripts', dest: '.config/hypr/' }


    - name: "Hyprland | Update configuration templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ ansible_user_dir }}/.config/hypr/{{ item.dest }}"
        backup: no
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      loop:
        - { src: 'autostart.conf.j2', dest: 'config/autostart.conf' }
        - { src: 'env_default.conf.j2', dest: 'config/environments/default.conf' }
        - { src: 'environment.conf.j2', dest: 'config/environment.conf' }
        - { src: 'hyprlock.conf.j2', dest: 'hyprlock.conf' }


- name: Manage Hyprland dynamic cursors
  block:
    - name: Update hyprpm package list
      command: hyprpm update

    - name: Install hypr-dynamic-cursors if not already installed
      block:
        - name: Check if hypr-dynamic-cursors is installed
          command: hyprpm list installed | grep dynamic-cursors
          register: dynamic_cursors_installed
          ignore_errors: true

        - name: Add hypr-dynamic-cursors repository
          command: yes "Y" | hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
          when: dynamic_cursors_installed.rc != 0

        - name: Install hypr-dynamic-cursors
          command: hyprpm install dynamic-cursors
          when: dynamic_cursors_installed.rc != 0

    - name: Enable dynamic cursors
      command: hyprpm enable dynamic-cursors
