---
- name: DotFiles Config
  hosts: all
  gather_facts: yes
  tasks:
    # Define the order of roles to run
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ default_roles }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    # Loop through roles in the specified order
    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags:
        - always
