---
- name: "Custom Apps | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: custom_apps_distribution_config

- name: "Custom Apps | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: custom_apps_distribution_config.stat.exists

#- name: "Gather package facts"
#  ansible.builtin.package_facts:


