---
- name: Install bluetooth packages | {{ ansible_distribution }}
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present
  become: true

- name: Pluseaudio Bluetooth Support  {{ ansible_distribution }}
  community.general.pacman:
    name:
      - pulseaudio-bluetooth
    state: present
  become: true
  when:
    - enable_bluetooth
    - audio_server == "pulseaudio"
