---
- name: "Bluetooth Support | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: bluetooth_distribution_config
  when: enable_bluetooth
  
- name: "Bluetooth Support | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: 
    - bluetooth_distribution_config.stat.exists
    - enable_bluetooth
