---
- name: Install Greetd & ags
  block:
    - name: Install Greetd Packages | {{ ansible_distribution }}
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - greetd
        - cage
    
    - name: Install Greetd Config AUR Dependencies | {{ ansible_distribution }}
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: present
        use: "{{ pacman.aur_helper }}"
      become: false
      loop:
        - aylurs-gtk-shell-git
