---
- name: "System | {{ ansible_distribution }} | Install System Compatibility Packages"
  community.general.pacman:
    name: 
      - xdg-user-dirs
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - fuse2
      - qt6-wayland
      - qt5-wayland
      - gtk4
      - libadwaita
    state: present
  become: true

- name: "Pipewire | {{ ansible_distribution }} | Install Pipewire"
  community.general.pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - pipewire-session-manager
      - wireplumber
    state: present
  become: true
  when: system.audio_server == "pipewire"

- name: "Plulseaudio | {{ ansible_distribution }} | Install Pluseaudio"
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-jack
    state: present
  become: true
  when: system.audio_server == "pluseaudio"

- name: Install bluetooth packages | {{ ansible_distribution }}
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present
  become: true
  when: 
    - system.enable_bluetooth

- name: Pluseaudio Bluetooth Support  {{ ansible_distribution }}
  community.general.pacman:
    name:
      - pulseaudio-bluetooth
    state: present
  become: true
  when:
    - system.enable_bluetooth
    - system.audio_server == "pulseaudio"
