---
- name: "Zsh | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: zsh_distribution_config
  when: system.default_shell == "zsh"

- name: "Zsh | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when:
    - system.default_shell == "zsh" 
    - zsh_distribution_config.stat.exists
  

- name: "Zsh | Configure Zsh"
  ansible.builtin.copy:
    src: zsh/.zshrc
    dest: "{{ ansible_user_dir }}/"
    mode: "0644"
    directory_mode: "0755"
    force: true
  when: system.default_shell == "zsh"
