---
- name: "Core Apps | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: core_apps_distribution_config

- name: "Core Apps | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: core_apps_distribution_config.stat.exists

- name: "Copy configuration files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
  with_items:
    - 'alacritty'
    - 'fastfetch'
    - 'helix'
    - 'oh-my-posh'

- name: "Copy zsh configuration file"
  ansible.builtin.copy:
    src: 'zsh/.zshrc'
    dest: '{{ ansible_user_dir }}/'
    mode: "0644"
    directory_mode: "0755"
    force: true
  when: system.default_shell == "zsh"

- name: Disable Oh My Posh Update Warnings
  command: oh-my-posh disable notice
