---
- name: "Core Apps | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: core_apps_distribution_config

- name: "Core Apps | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: core_apps_distribution_config.stat.exists

- name: "Gather package facts"
  ansible.builtin.package_facts:

- name: "Copy configuration files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    mode: "0644"
    directory_mode: "0755"
    force: true
  loop:
    - { src: 'alacritty', dest: '.config/alacritty', package: 'alacritty' }
    - { src: 'fastfetch', dest: '.config/fastfetch', package: 'fastfetch' }
    - { src: 'helix', dest: '.config/helix', package: 'helix' }
    - { src: 'oh-my-posh', dest: '.config/oh-my-posh', package: 'oh-my-posh-bin' }
  when: item.package in ansible_facts.packages

- name: "Copy zsh configuration file"
  ansible.builtin.copy:
    src: 'zsh/.zshrc'
    dest: '{{ ansible_user_dir }}/'
    mode: "0644"
    directory_mode: "0755"
    force: true
  when: system.default_shell == "zsh"

- name: Disable Oh My Posh Update Warnings
  command: oh-my-posh disable notice
