---
- name: Update pacman configuration file
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: no
    owner: root
    group: root
    mode: 0644
  become: true

