---
- name: "Update {{ system.default_shell }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "pre_tasks/aur_wrapper/{{ ansible_distribution }}.yml"
  register: shell_distribution_config

- name: "Update {{ system.default_shell }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: shell_distribution_config.stat.exists

- name: Ensure {{ system.default_shell }} is set for current user
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "/bin/{{ system.default_shell }}"
  become: true
