---
- name: "Alacritty | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: tmux_distribution_config

- name: "Alacritty | Configure Alacritty"
  ansible.builtin.copy:
    src: alacritty
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Alacritty | Configure tmux"
  ansible.builtin.copy:
    src: alacritty
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
