---
- name: "Alacritty | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: alacritty_distribution_config

- name: "Alacritty | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: alacritty_distribution_config.stat.exists

- name: "Alacritty | Configure Alacritty"
  ansible.builtin.copy:
    src: alacritty
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
