---
- name: Install Common Graphics Packages | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when: "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower() or 'intel' in gpu_result.stdout.lower()"
  loop:
    - mesa
    - mesa-utils

- name: Install lib32 Common Graphics Packages | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - pacman.enable_multilib 
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower() or 'intel' in gpu_result.stdout.lower()"
  loop:
    - lib32-mesa
    - lib32-mesa-utils

- name: Install GPU Drivers (AMD) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when: "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"
  loop:
    # https://wiki.archlinux.org/title/Xorg
    - xf86-video-amdgpu
    # https://wiki.archlinux.org/title/Hardware_video_acceleration
    - mesa-vdpau
    - libva-mesa-driver
    # https://wiki.archlinux.org/title/Vulkan
    - vulkan-radeon
    # https://wiki.archlinux.org/title/GPGPU
    - rocm-hip-runtime
    - rocm-hip-sdk
    - hip-runtime-amd
    - rocm-core
    - rocm-opencl-runtime
    - rocm-opencl-sdk

- name: Install 32bit GPU Drivers (AMD) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - pacman.enable_multilib 
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"
  loop:
    - lib32-vulkan-radeon
    - lib32-vulkan-icd-loader

- name: Remove linux-firmware
  community.general.pacman:
    name: linux-firmware
    state: absent
  become: true
  when:
    - gpu.proprietary_drivers    
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"

- name: Replace linux-firmware with linux-firmware-git
  kewlfft.aur.aur:
    name: linux-firmware-git
    state: present
  become: false
  when:
    - gpu.proprietary_drivers
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"

- name: Install GPU Drivers (AMD, Proprietary, Latest/Upstream) | {{ ansible_distribution }}
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: false
  when:
    - gpu.proprietary_drivers 
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"
  loop:
    - amdgpu-pro-oglp
    - vulkan-amdgpu-pro
    - amf-amdgpu-pro

- name: Install 32bit GPU Drivers (AMD, Proprietary, Latest/Upstream) | {{ ansible_distribution }}
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  become: false
  when:
    - pacman.enable_multilib
    - gpu.proprietary_drivers
    - "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"
  loop:
    - lib32-amdgpu-pro-oglp
    - lib32-vulkan-amdgpu-pro

- name: Install GPU Drivers (Intel) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when: "'intel' in gpu_result.stdout.lower()"
  loop:
    # https://wiki.archlinux.org/title/Xorg
    - xf86-video-intel
    # https://wiki.archlinux.org/title/Hardware_video_acceleration
    - intel-media-driver
    - libva-intel-driver
    # https://wiki.archlinux.org/title/Vulkan
    - vulkan-intel
    # https://wiki.archlinux.org/title/GPGPU
    - intel-compute-runtime
    - opencl-clover-mesa

- name: Install 32bit GPU Drivers (Intel) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - pacman.enable_multilib 
    - "'intel' in gpu_result.stdout.lower()"
  loop:
    - lib32-vulkan-intel
    - lib32-vulkan-icd-loader

- name: Install GPU Drivers (Nvidia, Proprietary, Latest/Upstream) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - "'nvidia' in gpu_result.stdout.lower()"
    - gpu.proprietary_drivers
  loop:
    # https://wiki.archlinux.org/title/NVIDIA
    - nvidia
    - nvidia-utils
    - cuda
    - opencl-nvidia

- name: Install 32bit GPU Drivers (Nvidia, Proprietary, Latest/Upstream) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - pacman.enable_multilib
    - "'nvidia' in gpu_result.stdout.lower()"
    - gpu.proprietary_drivers
  loop:
    - lib32-nvidia-utils
    - lib32-vulkan-icd-loader
    
- name: Install GPU Drivers (Nvidia, Nouveau Dependencies) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - "'nvidia' in gpu_result.stdout.lower()"
    - not gpu.proprietary_drivers
  loop:
    # https://wiki.archlinux.org/title/Nouveau
    - xf86-video-nouveau
    - vulkan-nouveau

- name: Install lib32 GPU Drivers (Nvidia, Nouveau Dependencies) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - pacman.enable_multilib
    - "'nvidia' in gpu_result.stdout.lower()"
    - not gpu.proprietary_drivers
  loop:
    - lib32-mesa
    - lib32-mesa-utils  
    
