---
- name: Install Common Graphics Packages | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - mesa
    - mesa-utils

- name: Install GPU Drivers (AMD) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when: "'amd' in gpu_result.stdout.lower() or 'radeon' in gpu_result.stdout.lower()"
  loop:
    # https://wiki.archlinux.org/title/Xorg
    - xf86-video-amdgpu
    # https://wiki.archlinux.org/title/Hardware_video_acceleration
    - mesa-vdpau
    - libva-mesa-driver
    # https://wiki.archlinux.org/title/Vulkan
    - vulkan-radeon
    # https://wiki.archlinux.org/title/GPGPU
    - rocm-hip-runtime
    - rocm-hip-sdk
    - hip-runtime-amd
    - rocm-core
    - rocm-opencl-runtime
    - rocm-opencl-sdk

- name: Install GPU Drivers (Intel) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when: "'intel' in gpu_result.stdout.lower()"
  loop:
    # https://wiki.archlinux.org/title/Xorg
    - xf86-video-intel
    # https://wiki.archlinux.org/title/Hardware_video_acceleration
    - intel-media-driver
    - libva-intel-driver
    # https://wiki.archlinux.org/title/Vulkan
    - vulkan-intel
    # https://wiki.archlinux.org/title/GPGPU
    - intel-compute-runtime
    - opencl-clover-mesa

- name: Install GPU Drivers (Nvidia, Proprietary, Latest/Upstream) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - "'nvidia' in gpu_result.stdout.lower()"
    - gpu.nvidia.proprietary_nvidia_drivers
  loop:
    # https://wiki.archlinux.org/title/NVIDIA
    - nvidia
    - nvidia-utils
    - cuda
    - opencl-nvidia

- name: Install GPU Drivers (Nvidia, Nouveau Dependencies) | {{ ansible_distribution }}
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  when:
    - "'nvidia' in gpu_result.stdout.lower()"
    - not gpu.nvidia.proprietary_nvidia_drivers
  loop:
    # https://wiki.archlinux.org/title/Nouveau
    - xf86-video-nouveau
    - vulkan-nouveau
