---
- name: "Oh My Posh | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: oh_my_posh_distribution_config

- name: "Oh My Posh | Configure Oh My Posh"
  ansible.builtin.copy:
    src: oh-my-posh
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Oh My Posh | Configure Oh My Posh"
  ansible.builtin.copy:
    src: oh-my-posh
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
